# font          = monospace 8
font          = fixed 9

bg_normal     = #333333aa
bg_focus      = #454545aa
bg_urgent     = #ffd700aa

fg_normal     = #999999
fg_focus      = #ffffff
fg_urgent     = #111111

border_width  = 2
border_normal = #000000
border_focus  = #454545
border_marked = #91231c

taglist_squares_sel = /usr/local/share/awesome/themes/default/taglist/squarefw.png
taglist_squares_unsel = /usr/local/share/awesome/themes/default/taglist/squarew.png
