# font          = monospace 8
font          = fixed 9

bg_normal     = #333333
bg_focus      = #656565
bg_urgent     = #ffd700

fg_normal     = #999999
fg_focus      = #ffffff
fg_urgent     = #111111

border_width  = 2
border_normal = #333333
border_focus  = #656565

taglist_squares_sel          = /usr/local/share/awesome/themes/default/taglist/squarefw.png
taglist_squares_unsel        = /usr/local/share/awesome/themes/default/taglist/squarew.png
tasklist_floating_icon       = /usr/local/share/awesome/themes/default/tasklist/floatingw.png

titlebar_close_button_normal = /usr/local/share/awesome/themes/default/titlebar/close.png
titlebar_close_button_focus  = /usr/local/share/awesome/themes/default/titlebar/closer.png
